# How to author Executors: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
description: >
 This is the executor that must get used with a f0cal job since we need a vpn at the moment
machine:
  image: ubuntu-1604:201903-01
